#!/usr/bin/env ruby
# encoding: utf-8

require 'sanfrecce'
require 'sanfrecce/version'
require 'thor'
require 'pp'

module Sanfrecce
  # = Sanfrecce CLI
  class CLI < Thor
    class_option :help, type: :boolean, aliases: '-h', desc: 'help message.'
    class_option :version, type: :boolean, desc: 'version'
    class_option :debug, type: :boolean, aliases: '-d', desc: 'debug mode'

    desc 'version', 'version'
    def version
      p Sanfrecce::VERSION
    end

    desc 'players', 'player list'
    def players
      pp Sanfrecce.players
    end

    desc 'number', 'player number'
    def number(no = 11)
      p Sanfrecce.players[no]
    end

    desc 'games', 'all games'
    def games
      hoge = Sanfrecce.all_games
      pp hoge
    end

    desc 'game', 'game result'
    def game(no = 1)
      pp Sanfrecce.first_stage['1st-' + no]
    end
  end
end

Sanfrecce::CLI.start(ARGV)
